### PR TITLE
Add Kube based deployment

### PR DESCRIPTION
**Pull request by eyakubovich**
Adds DaemonSet based deployment. Since the modern k8s no longer uses Docker, the agent will not be able to see the containers. Support for CRI/containerd based introspection is coming next.

### CODE REVIEW

**Review by robszumski — APPROVED** [review]
Looks great! I wonder if we should be more specific about namespace name since some platforms will need additional RBAC rules to allow privileged containers, and you wouldn't put that in `default`.

**Comment by eyakubovich** [comment]
Good point on the namespace, how should we make it explicit? Should we force the user to fill it in via `namespace: PUT_NS_HERE`?

**Comment by robszumski** [comment]
> Good point on the namespace, how should we make it explicit?

I vote using something like `edgebit` or `edgebit-system` so it all works out of the box and then folks can change it if they want.

Thinking through permissions, I wonder if we want to have `edgebit-node` and `edgebit-cluster` so that each are well isolated from each other, since they will need distinct but fairly powerful permissions, eg. priv for the node agent and view all pods for the cluster agent.

**Review by robszumski — APPROVED** [review]
Docs and `edgebit-system` LGTM

**Pull request merged**
