### PR TITLE
Send report-in-use heartbeats every 5 mins

### PR DESCRIPTION
**Pull request by eyakubovich**
In case where there's no activity (new files in-use), send an empty report as a heartbeat every 5 mins.

### CODE REVIEW

**Review by robszumski — APPROVED** [review]
LGTM

**Review by russellhaering — COMMENTED** [review]
Can we put some kind of jitter on these?

**Comment by eyakubovich** [comment]
Are you concerned that all the machines will line up? Seems unlikely.

**Comment by russellhaering** [comment]
Yeah, we should treat this as a best practice for agents since they'll tend to be managed in groups (via DaemonSet, some other config management, etc).

**Review by russellhaering — APPROVED** [review]
LGTM

**Pull request merged**
